id = "tombi"
name = "Tombi | TOML Toolkit"
version = "0.2.1"
description = "ðŸ¦…  TOML Language Server  ðŸ¦…"
schema_version = 1
authors = ["tombi-toml <tombi-toml@outlook.com>"]
repository = "https://github.com/tombi-toml/tombi"

[language_servers.tombi]
name = "Tombi"
languages = ["TOML"]
