[alias]
decode = "run --package toml-test --bin decode --"
jsonschema = "run --package config --bin jsonschema --all-features --"
tombi = "run --package tombi-cli --bin tombi --"
tombi-flamegraph = "flamegraph --output .tmp/flamegraph.svg --package tombi-cli --"
xtask = "run --package xtask --bin xtask --"
parse-jsonschema = "run --package tombi-schema-store --example parse_jsonschema --"

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", 'getrandom_backend="wasm_js"']
