[package]
name = "tombi-extension"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tombi-ast.workspace = true
tombi-document-tree.workspace = true
tombi-schema-store.workspace = true
tombi-text.workspace = true
tombi-uri.workspace = true
tower-lsp.workspace = true
