[package]
name = "tombi-comment-directive"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ahash.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tombi-ast.workspace = true
tombi-diagnostic.workspace = true
tombi-document = { workspace = true, features = ["serde"] }
tombi-document-tree.workspace = true
tombi-json.workspace = true
tombi-parser.workspace = true
tombi-schema-store.workspace = true
tombi-text.workspace = true
tombi-toml-version.workspace = true
tombi-uri.workspace = true
tombi-validator.workspace = true

[features]
jsonschema = ["dep:schemars", "tombi-toml-version/jsonschema"]
